### ISSUE TITLE
PEP for 2D data

### ISSUE THREAD

**Issue by rajmis** [thangbui/sparseGP_powerEP#1]
Can you please provide an example for 2D data? It is throwing errors if I modify the existing test script.

**Comment by thangbui** [comment]
Thanks for the interest in the code. 

Could you provide an example? Are you trying to use the matlab or python version of the code and are you interested in regression or classification?

For regression, both GPML (matlab) and GPy (python) have now supported Power-EP and the limits (VFE and FITC/EP).

**Comment by rajmis** [comment]
Thank you for the reply 👍 

Example - Regression over temperature data of an area. 
And I was using the MATLAB version of the code as I am still prototyping things but once I am done, I'll shift to the python version (probably using GPflow)

I ran the GPML code (for FITC) but didn't get the same results as Snelson's [code](http://www.gatsby.ucl.ac.uk/~snelson/SPGP_dist.zip). I am using a squared exponential ARD kernel and initialised the hyper-parameters using a full GP regression on a random subset.

**Comment by konschti** [comment]
Using MATLAB and looking at test_sgp I could not figure out how to modify the test code to accept multiple input dimensions for a regression problem (eg similar to section 4.1 of the paper?
Could you please give an example code for that use case?

**Comment by thangbui** [comment]
@rajmis If both use the same optimizer and the same initialisation, they should give the same results. Could you please provide a concrete code example where there is a difference so I could look into?

@rajmis  @konschti It should look something like this -- basically, you need to change the pseudo-inputs and length-scales, and make sure their shapes match that of the original training inputs (e.g. hyp_cell.l should be a Dx1 vector and p.induce should be a MxD matrix): 

```
N_train = size(X_train, 1);
D = size(X_train, 2);    
xu_ind = randperm(s, size(X_train, 1), M);
xu = X_train(xu_ind, :);
xdist = sqrt(pdist2(X_train, X_train));
xdist_vec = xdist(triu(ones(N_train))==1);
median_dist = median(xdist_vec);
if median_dist == 0; 
    median_dist = 0.1; 
end   

style.name = 'pep';
style.alpha = alpha;
style.linear_mean = 0;
hyp_cell.l = log(2*median_dist)*ones(D, 1);
hyp_cell.s = 0;
hyp_cell.n = log(0.05);
hyp_cell.m = zeros(D, 1);
hyp_cell.b = 0;
p.hyp = hyp_cell;
p.induce = xu;

% we train the model
[p_opt, nlml, no_evals] = minimize(p, @sgp, -max_evals, X_train, y_train, style);

% we get the predictive marginal means and variances 
 [m s2] = sgp(p_opt, X_train, y_train, style, X_test);
```

**Comment by konschti** [comment]
Great. Thank you vm.
